fetch("https://www.coursehubiitg.in/api/codingweek/contributions")
.then(response => response.json())
.then(data => {
  let a=document.querySelector("#name1")
  a.innerHTML= `${data[4].name} ${data[4].points}`
  let b=document.querySelector("#name2")
  b.innerHTML= `${data[5].name} ${data[5].points}`
  let c=document.querySelector("#name3")
  c.innerHTML= `${data[7].name} ${data[7].points}`
  let d=document.querySelector("#name4")
  d.innerHTML= `${data[2].name}`
  let e=document.querySelector("#name5")
  e.innerHTML= `${data[1].name}`
  let f=document.querySelector("#name6")
  f.innerHTML= `${data[0].name}`
  let g=document.querySelector("#name7")
  g.innerHTML= `${data[6].name}`
  let h=document.querySelector("#name8")
  h.innerHTML= `${data[3].name}`
  let i=document.querySelector("#points4")
  i.innerHTML= `${data[2].points}`
  let j=document.querySelector("#points5")
  j.innerHTML= `${data[1].points}`
  let k=document.querySelector("#points6")
  k.innerHTML= `${data[0].points}`
  let l=document.querySelector("#points7")
  l.innerHTML = data[6].points
  let m=document.querySelector("#points8")
  m.innerHTML = data[3].points
  let n=document.querySelector("#face1")
  n.src= data[4].avatar
  let o=document.querySelector("#face2")
  o.src = data[5].avatar
  let p=document.querySelector("#face3")
  p.src= data[7].avatar
  let q=document.querySelector("#face4")
  q.src = data[2].avatar
  let r=document.querySelector("#face5")
  r.src= data[1].avatar
  let s=document.querySelector("#face6")
  s.src = data[0].avatar
  let t=document.querySelector("#face7")
  t.src= data[6].avatar
  let u=document.querySelector("#face8")
  u.src = data[3].avatar
})
